content_strategy_task:
  description: >
    Create a detailed outline for a blog post about {topic}.
    Identify the key points, structure, and audience tone that will resonate best.
    Provide a brief explanation for each section's importance and suggest a call-to-action (CTA).
  expected_output: >
    A structured outline with the following:
    - Title of the blog
    - Headings and subheadings
    - Brief explanation of each section
    - Suggested call-to-action (CTA)
  agent: Content_Strategist

content_creation_task:
  description: >
    Write a complete blog post based on the provided outline for {topic}.
    Make the content engaging, informative, and tailored to the intended audience.
    Use a conversational tone and include examples, code, or data points to make it relatable.
  expected_output: >
    A well-written blog post formatted in markdown (without '```') with:
    - Engaging introduction
    - Detailed sections based on the outline
    - A concise and compelling conclusion
  agent: Creative_Blogger

seo_optimization_task:
  description: >
    Optimize the completed blog post about {topic} for search engines.
    Research and identify relevant keywords for the topic and seamlessly integrate them into the blog content.
    Revise the title to be SEO-friendly while maintaining reader engagement.
    Improve readability and formatting for a better user experience and search ranking.
  expected_output: >
    An optimized version of the blog post with:
    - Keywords naturally incorporated into the content
    - A revised, SEO-friendly title integrated into the blog
    - Inline improvements to readability, structure, or flow, if necessary
    - dont include the preamble, blog need to start with title and end with conclusion.
    - the response should be in html format only body part. and body should have 2 divs, one for title and another for content.
    for headings give strong tag
  agent: SEO_Analyst
