content_strategy_task:
  description: >
    Create a detailed outline for a blog post about {topic}.
    Identify the key points, structure, and audience tone that will resonate best.
    Provide a brief explanation for each section's importance and suggest a call-to-action (CTA).
  expected_output: >
    A structured outline with the following:
    - Title of the blog
    - Headings and subheadings
    - Brief explanation of each section
    - Suggested call-to-action (CTA)
  agent: Content_Strategist

content_creation_task:
  description: >
    Write a complete blog post based on the provided outline for {topic}.
    Make the content engaging, informative, and tailored to the intended audience.
    Use a conversational tone and include examples, code, or data points to make it relatable.
  expected_output: >
    A well-written blog post formatted in markdown (without '```') with:
    - Engaging introduction
    - Detailed sections based on the outline
    - A concise and compelling conclusion
  agent: Creative_Blogger

seo_optimization_task:
  description: >
    Optimize the completed blog post about {topic} for search engines.
    Research relevant keywords for the topic and integrate them naturally into the content.
    Write a meta description, create an SEO-friendly title, and suggest any improvements for better readability and ranking.
  expected_output: >
    An optimized version of the blog post with:
    - Keywords highlighted and naturally incorporated
    - SEO-friendly title and meta description
    - Suggestions for additional improvements if needed
  agent: SEO_Analyst
